/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class View_GameUI extends View {
		public over:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("View_Game");
        }
    }
    REG("ui.View_GameUI",View_GameUI);
    export class View_LoadingUI extends View {
		public loading_bg:Laya.Image;
		public loading_line:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("View_Loading");
        }
    }
    REG("ui.View_LoadingUI",View_LoadingUI);
    export class View_MainUI extends View {
		public ani1:Laya.FrameAnimation;
		public start:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("View_Main");
        }
    }
    REG("ui.View_MainUI",View_MainUI);
}