/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.Views {
    export class View_LoadingUI extends View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/View_Loading");
        }
    }
    REG("ui.Views.View_LoadingUI",View_LoadingUI);
}